FROM jupyter/base-notebook:notebook-6.5.4

ADD ./requirements.txt .
RUN pip install -r requirements.txt \
  && rm ./requirements.txt
 
USER root

RUN jupyter contrib nbextension install && \
  jupyter nbextension enable --py --sys-prefix ipyleaflet && \
  jupyter serverextension enable --py --sys-prefix nbgitpuller && \
  jupyter nbextension enable rubberband/main && \
  jupyter nbextension enable exercise2/main 

USER $NB_UID
